name: fsrs
description: Dart Package for FSRS
version: 1.0.0
repository: https://github.com/sonbui00/dart-fsrs

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
